<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Profiles', 'doctrine');

/**
 * BaseProfiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $nickname
 * @property string $email
 * @property Users $Users
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method string   getName()     Returns the current record's "name" value
 * @method string   getSurname()  Returns the current record's "surname" value
 * @method string   getNickname() Returns the current record's "nickname" value
 * @method string   getEmail()    Returns the current record's "email" value
 * @method Users    getUsers()    Returns the current record's "Users" value
 * @method Profiles setId()       Sets the current record's "id" value
 * @method Profiles setName()     Sets the current record's "name" value
 * @method Profiles setSurname()  Sets the current record's "surname" value
 * @method Profiles setNickname() Sets the current record's "nickname" value
 * @method Profiles setEmail()    Sets the current record's "email" value
 * @method Profiles setUsers()    Sets the current record's "Users" value
 * 
 * @package    simplenews
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfiles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profiles');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('surname', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('nickname', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}