<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Roles', 'doctrine');

/**
 * BaseRoles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $name
 * @property Doctrine_Collection $Users
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method enum                getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getUsers() Returns the current record's "Users" collection
 * @method Roles               setId()    Sets the current record's "id" value
 * @method Roles               setName()  Sets the current record's "name" value
 * @method Roles               setUsers() Sets the current record's "Users" collection
 * 
 * @package    simplenews
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('roles');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'enum', 9, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'author',
              1 => 'editor',
              2 => 'anonymous',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 9,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Users', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}