generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Comments
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          comments
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
       display: [author_name,_text,published_at,_published,article_title]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
