generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Articles
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          articles
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
       table_method: getArticlesByCredential
       display: [title,text,c_name,published_at,read_count,u_name,published,photo]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
