generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Articles
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          articles
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
       title: {label: Title}
       text: {label: Text}
       c_name: {label: Category}
       published_at: {label: Published at}
       read_count: {label: Read}
       author: {label:Author}
       published: {label:Published}
       photo: {label:Image}
      list:
       table_method: getArticlesByCredential
       display: [title,_text,c_name,published_at,read_count,author,_published,_photo]
      filter:  ~ 
      form:    ~
      edit:    ~
      new:     ~
