<?php

/**
 * Articles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simplenews
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Articles extends BaseArticles
{




	public function getCategoryName()
	{

		return $this->getCategories()->getName();
	}


	public function getAuthorName()
	{

	 $ime = $this->getUsers()->getName();
  	 $prezime = $this->getUsers()->getSurname();
  
  	 return $ime.' '.$prezime;
  	
	}

	public function getArttags()
	{

	  return implode(',',$this->getTags()->getText());
	}

}