<?php

/**
 * ArticlesTagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticlesTagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticlesTagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticlesTags');
    }
}