<?php

/**
 * CategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categories');
    }
}