<?php

/**
 * CommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comments');
    }
    
    
  /**
   *  Prima ID clanka i varijablu published: 1 ili 0. Vrsi update samo property-ja 'published'.
   *  Akcija pokrenuta iz ajax-a
   */
  public function updateComment($id,$pub)
  {
    $q = $this->createQuery()
        ->update('Comments')
        ->set('published','?',$pub)
        ->where('id=?',$id);

    $q->execute();
    return 'ok';
  }


  /**
     * 'Selecta' jedan komentar za prikaz u dialogbox-u
     * 
     * @param integer comments.id
     */

    public function getOneComment($id)
    {
      $q = $this->createQuery()
      ->from('Comments c')
      ->where('c.id=?',$id);
     
      return $q->fetchOne();
    }
}