<?php

/**
 * Comments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    simplenews
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comments extends BaseComments
{

 
  /**
  *
  *  Vraca naslov clanka za prikaz komentara u backend app, polje navedeno u generator.yml
  */
  public function getArticleTitle()
  {

   return $this->getArticles()->getTitle();

  }


/**
* Vraca ime ili nickname autora komentara, umjesto ID-a. (Backend lista komentara)
*
*/
  public function getAuthorName()
  {
  	$ime = $this->getUsers()->getName();
  	$prezime = $this->getUsers()->getSurname();
    $nick = $this->getUsers()->getNickname();

    if(!empty($ime)):
  	  return $ime.' '.$prezime;
  	else:
  	  return $nick;
  	endif;
  }
}