<?php

/**
 * ProfilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Profiles');
    }
}