<?php

/**
 * UsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Users');
    }
    
    
    /**
     *  'Selecta' korisnika na osnovu username-a i vraca objekt ako taj user postoji 
     */
    public function verifyUser($username,$password)
    {
     $user_res = $this->createQuery("usr")
                 ->select("usr.username,usr.password,usr.id")
				 ->where("usr.username=?",$username)
                 ->fetchOne();

     if (is_object($user_res)) 
     {
      $usrnm = $user_res->getUsername();
      if(!empty($usrnm))
       {
        if(sha1($password)==$user_res->getPassword())
         {
          
          return array($usrnm,$user_res->getId(),true);
          
         }
        else
         {
          return array(false,false,false);
         }
       }
      else
       {
        return array(false,false,false);
       }    
     }
   
    }
    
    
    /**
     * 'Slaze' random password od slucajnih brojeva, za novog anonimnog korisnika 
     * 
     */
    public function createPassword()
    {
     $brojA = rand(0,1000);
     $brojB = rand(0,1000);
     
     $passwd = $brojA.$brojB;
     return $passwd;
    }
}