# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules

homepage:
  url:   /:sf_culture/
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
naslovnica:
  url:   /:sf_culture/naslovnica
  param: { module: home, action: index }

korisnik:
  url:   /:sf_culture/korisnik
  param: { module: user, action: index }

default_index:
  url:   /:sf_culture/:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
