generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tags
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tags
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
       text: {label:Tag text}
      list:
       display: [text]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
