# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/09-Cache

default:
  enabled:     false
  with_layout: false
  lifetime:    20

index:
  enabled:     true
  with_layout: false
  lifetime:    20

category:
  enabled:     true
  with_layout: false
  lifetime:    20

article:
  enabled:     true
  with_layout: false
  lifetime:    20

tagresult:
  enabled:     true
  with_layout: false
  lifetime:    20
