generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Users
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          users
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
       display: [role_name,username,active,name,surname,email,nickname]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
