Articles:
  connection: doctrine
  tableName: articles
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(180)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    text:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    category_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    published_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    read_count:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    published:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    photo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Categories:
      local: category_id
      foreign: id
      type: one
    Users:
      local: user_id
      foreign: id
      type: one
    Tags:
      class: Tags
      refClass: ArticlesTags
      local: Articles
      foreign: Tags
    Comments:
      local: id
      foreign: article_id
      type: many
ArticlesTags:
  connection: doctrine
  tableName: articles_tags
  columns:
    articles_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      notnull: true
      autoincrement: false
    tags_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      notnull: true
      autoincrement: false
  relations:
    Articles:
      foreignAlias: ArticlesTags
    Tags:
      foreignAlias: ArticlesTags

Categories:
  connection: doctrine
  tableName: categories
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Articles:
      local: id
      foreign: category_id
      type: many
Comments:
  connection: doctrine
  tableName: comments
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    text:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    article_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    published_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    published:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Users:
      local: user_id
      foreign: id
      type: one
    Articles:
      local: article_id
      foreign: id
      type: one
Roles:
  connection: doctrine
  tableName: roles
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: enum(9)
      fixed: false
      unsigned: false
      values:
        - author
        - editor
        - anonymous
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Users:
      local: id
      foreign: role_id
      type: many
Tags:
  connection: doctrine
  tableName: tags
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    text:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Articles:
      class: Articles
      refClass: ArticlesTags
      local: Tags
      foreign: Articles
Users:
  connection: doctrine
  tableName: users
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    role_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    username:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(90)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    active:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    surname:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nickname:
      type: string(60)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Roles:
      local: role_id
      foreign: id
      type: one
    Articles:
      local: id
      foreign: user_id
      type: many
    Comments:
      local: id
      foreign: user_id
      type: many
